import type { ModelName } from "./models";
import type { Quantization } from "./quantizations";

export type ModelSizeEstimateEntry = {
  name: ModelName;
  quantization: Quantization;
  sizeGb: number;
};

// This block is auto-generated by `bun run models:update`.
// Keep sorted by model name for stable diffs.
export const MODEL_SIZE_ESTIMATES_GB: ModelSizeEstimateEntry[] = [
  { name: "Gemma 4 12B", quantization: "Q4_K_M", sizeGb: 6.79 },
  { name: "Gemma 4 26B A4B", quantization: "Q4_K_M", sizeGb: 16.89 },
  { name: "LFM2.5 8B A1B", quantization: "Q4_K_M", sizeGb: 4.96 },
  { name: "Muse Glimmer 30B", quantization: "Q4_K_XL", sizeGb: 18.37 },
  { name: "Qwen3.6 35B A3B", quantization: "Q4_K_M", sizeGb: 21.45 },
  { name: "Qwen3.8 27B", quantization: "Q4_K_M", sizeGb: 16.2 },
  { name: "Qwen3.8 27B", quantization: "Q6_K_XL", sizeGb: 24.43 },
  { name: "Qwen3.8-Flash-Next", quantization: "Q4_K_XL", sizeGb: 104.54 },
];
