import type { ModelName } from "./models";
import type { Quantization } from "./quantizations";

export type ModelSizeEstimateEntry = {
  name: ModelName;
  quantization: Quantization;
  sizeGb: number;
};

// This block is auto-generated by `bun run models:update`.
// Keep sorted by model name for stable diffs.
export const MODEL_SIZE_ESTIMATES_GB: ModelSizeEstimateEntry[] = [
  { name: "Gemma 4 26B A4B", quantization: "Q4_K_M", sizeGb: 15.78 },
  { name: "GLM 4.7 Flash", quantization: "Q4_K_M", sizeGb: 17.05 },
  { name: "GPT OSS 20B", quantization: "MXFP4", sizeGb: 11.28 },
  { name: "Mistral Small 4", quantization: "Q4_K_M", sizeGb: 68.7 },
  { name: "Qwen3 4B Instruct 2507", quantization: "Q8_0", sizeGb: 3.99 },
  { name: "Qwen3 Coder Next", quantization: "Q4_K_M", sizeGb: 45.92 },
  { name: "Qwen3 VL 32B Instruct", quantization: "Q6_K_XL", sizeGb: 28.87 },
  { name: "Qwen3 VL 4B Instruct", quantization: "Q4_K_M", sizeGb: 4.23 },
  { name: "Qwen3 VL 8B Instruct", quantization: "Q4_K_M", sizeGb: 6.58 },
  { name: "Qwen3.5 122B A10B", quantization: "Q4_K_M", sizeGb: 71.28 },
  { name: "Qwen3.6 27B", quantization: "Q4_K_M", sizeGb: 15.66 },
  { name: "Qwen3.6 35B A3B", quantization: "Q4_K_M", sizeGb: 20.61 },
];
