import type { ModelName } from "./models";
import type { Quantization } from "./quantizations";

export type ModelSizeEstimateEntry = {
  name: ModelName;
  quantization: Quantization;
  sizeGb: number;
};

// This block is auto-generated by `bun run models:update`.
// Keep sorted by model name for stable diffs.
export const MODEL_SIZE_ESTIMATES_GB: ModelSizeEstimateEntry[] = [
  { name: "Gemma 4 12B", quantization: "Q4_K_M", sizeGb: 6.90 },
  { name: "Gemma 4 26B A4B", quantization: "Q4_K_M", sizeGb: 15.78 },
  { name: "Gemma 4 31B", quantization: "Q4_K_M", sizeGb: 17.83 },
  { name: "LFM2.5 8B A1B", quantization: "Q4_K_M", sizeGb: 4.60 },
  { name: "Qwen3 Coder Next", quantization: "Q4_K_M", sizeGb: 45.92 },
  { name: "Qwen3.5 9B", quantization: "Q4_K_M", sizeGb: 5.18 },
  { name: "Qwen3.6 27B", quantization: "Q4_K_M", sizeGb: 15.66 },
  { name: "Qwen3.6 27B", quantization: "Q6_K_XL", sizeGb: 23.18 },
  { name: "Qwen3.6 35B A3B", quantization: "Q4_K_M", sizeGb: 20.61 },
];
